spring.datasource.url=jdbc:h2:mem:paymentgateway;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379
management.health.redis.enabled=true

idempotency.ttl-hours=24

payment.gateway.stripe.base-url=https://api.stripe.com
payment.gateway.stripe.api-key=sk_test_mock_key_local
payment.gateway.paypal.base-url=https://api-m.sandbox.paypal.com

jwt.secret=payment-gateway-super-secret-key-minimum-256-bits-long
jwt.expiration-ms=3600000

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always

resilience4j.circuitbreaker.instances.stripe.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.stripe.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.stripe.sliding-window-size=5
resilience4j.circuitbreaker.instances.paypal.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paypal.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.paypal.sliding-window-size=5